services:
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://db:27017/db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data: